module.exports = [
    { id: 1, name: 'Acre', initial: 'AC', country_id: 1 },
    { id: 2, name: 'Alagoas', initial: 'AL', country_id: 1 },
    { id: 3, name: 'Amazonas', initial: 'AM', country_id: 1 },
    { id: 4, name: 'Amapá', initial: 'AP', country_id: 1 },
    { id: 5, name: 'Bahia', initial: 'BA', country_id: 1 },
    { id: 6, name: 'Ceará', initial: 'CE', country_id: 1 },
    { id: 7, name: 'Distrito Federal', initial: 'DF', country_id: 1 },
    { id: 8, name: 'Espírito Santo', initial: 'ES', country_id: 1 },
    { id: 9, name: 'Goiás', initial: 'GO', country_id: 1 },
    { id: 10, name: 'Maranhão', initial: 'MA', country_id: 1 },
    { id: 11, name: 'Minas Gerais', initial: 'MG', country_id: 1 },
    { id: 12, name: 'Mato Grosso do Sul', initial: 'MS', country_id: 1 },
    { id: 13, name: 'Mato Grosso', initial: 'MT', country_id: 1 },
    { id: 14, name: 'Pará', initial: 'PA', country_id: 1 },
    { id: 15, name: 'Paraíba', initial: 'PB', country_id: 1 },
    { id: 16, name: 'Pernambuco', initial: 'PE', country_id: 1 },
    { id: 17, name: 'Piauí', initial: 'PI', country_id: 1 },
    { id: 18, name: 'Paraná', initial: 'PR', country_id: 1 },
    { id: 19, name: 'Rio de Janeiro', initial: 'RJ', country_id: 1 },
    { id: 20, name: 'Rio Grande do Norte', initial: 'RN', country_id: 1 },
    { id: 21, name: 'Rondônia', initial: 'RO', country_id: 1 },
    { id: 22, name: 'Roraima', initial: 'RR', country_id: 1 },
    { id: 23, name: 'Rio Grande do Sul', initial: 'RS', country_id: 1 },
    { id: 24, name: 'Santa Catarina', initial: 'SC', country_id: 1 },
    { id: 25, name: 'Sergipe', initial: 'SE', country_id: 1 },
    { id: 26, name: 'São Paulo', initial: 'SP', country_id: 1 },
    { id: 27, name: 'Tocantins', initial: 'TO', country_id: 1 }
];
