export const COLOR_BACKGROUND_ROW_HEAD_TABLES = '#f3f3f3';
export const NAME_COOKIES_USER_TOKEN = process.env.NEXT_PUBLIC_NAME_COOKIES_USER_TOKEN;
export const MESSAGE_ERROR_ALERT_CATCH = process.env.NEXT_PUBLIC_MESSAGE_ERROR_ALERT_CATCH;
export const API_HELPERS_URL = process.env.NEXT_PUBLIC_API_HELPERS_URL;
export const TOKEN_API_HELPERS = process.env.NEXT_PUBLIC_TOKEN_API_HELPERS;
