import { StyleSheet } from 'react-native';

import {
  stylesLayoutSafeAreaView,
  stylesLayoutContainerView,
  stylesLayoutContainerKeyboardAvoidingView,
  stylesLayoutContainerScrollView
} from './stylesLayout';

import {
  stylesDrawerLabelStyleDrawerItem
} from './stylesDrawer';

import {
  stylesCustomDrawerContainerView,
  stylesCustomDrawerImageLogo,
  stylesCustomDrawerTextWellcome,
  stylesCustomDrawerTextUserName,
  stylesCustomDrawerLabelStyleDrawerItem
} from './stylesCustomDrawer';

import {
  styleHeaderContainerSafeAreaView,
  styleHeaderContainerView,
  styleHeaderButtonMenuDrawer,
  styleHeaderButtonMenuAction,
  styleHeaderDividerMenuAction,
  styleHeaderIconLogo,
} from './stylesHeader';

import {
  stylesSnackbarWrapperStyle,
  stylesSnackbarTitleHeader,
  stylesSnackbarmsgText,
} from './stylesSnackbar';

import {
  stylesSignUpContainer,
  stylesSignUpTitleHeader,
  stylesSignUpTitle,
  stylesSignUpSubtitle,
  stylesSignUpFormItem,
  stylesSignUpFormButton,
  stylesSignUpFormButtonlabel,
  stylesSignUpFormButtonViewAccessLogin,
  stylesSignUpFormButtonTextAccessLogin,
  stylesSignUpAcceptConditionsView,
  stylesSignUpAcceptConditionsViewCheckbpx,
  stylesSignUpAcceptConditionsText,
} from './stylesSignUp';

import {
  stylesSignInContainer,
  stylesSignInTitleHeader,
  stylesSignInTitle,
  stylesSignInSubtitle,
  stylesSignInFormItem,
  stylesSignInFormButton,
  stylesSignInFormButtonlabel,
  stylesSignInFormButtonViewAccessLogin,
  stylesSignInFormButtonTextAccessLogin,
  stylesSignInAcceptConditionsView,
  stylesSignInAcceptConditionsViewCheckbpx,
  stylesSignInAcceptConditionsText,
} from './stylesSignIn';

import {
  stylesProfileContainer,
  stylesProfileTitleHeader,
  stylesProfileTitle,
  stylesProfileSubtitle,
  stylesProfileFormItem,
  stylesProfileFormButton,
  stylesProfileFormButtonlabel,
  stylesProfileFormButtonDesactive,
  stylesProfileFormButtonDesactiveText,
} from './stylesProfile';

import {
  stylesAlertYesOrNoIcon,
  stylesAlertYesOrNoIconError,
  stylesAlertYesOrNoIconSuccess,
  stylesAlertYesOrNoIconWarning,
  stylesAlertYesOrNoIconInfo,
  stylesAlertYesOrNoContainer,
  stylesAlertYesOrNoText,
  stylesAlertYesOrNoViewButton,
  stylesAlertYesOrNoButton,
  stylesAlertYesOrNoButtonLabel,
  stylesAlertYesOrNoTextTitle,
} from './stylesAlertYesOrNo';

import {
  stylesChangePasswordContainer,
  stylesChangePasswordTitleHeader,
  stylesChangePasswordTitle,
  stylesChangePasswordSubtitle,
  stylesChangePasswordFormItem,
  stylesChangePasswordFormButton,
  stylesChangePasswordFormButtonlabel,
  stylesChangePasswordFormButtonDesactive,
  stylesChangePasswordFormButtonDesactiveText,
} from './stylesChangePassword';

import {
  stylesResetPasswordContainer,
  stylesResetPasswordTitleHeader,
  stylesResetPasswordTitle,
  stylesResetPasswordSubtitle,
  stylesResetPasswordFormItem,
  stylesResetPasswordFormButton,
  stylesResetPasswordFormButtonlabel,
} from './stylesResetPassword';

import {
  stylesListsSystemContainer,
  stylesListsSystemFiltersView,
  stylesListsSystemFilterTextView,
  stylesListsSystemFilterText,
  stylesListsSystemContainerViewList,
  stylesListsSystemViewCard,
  stylesListsSystemCardRightStyle,
  stylesListsSystemCardTitleStyle,
  stylesListsSystemCardSubtitleStyle,
  stylesListsSystemListEmptyContainer,
  stylesListsSystemListEmptyTextMsg,
  stylesListsSystemListEmptyTextSubMsg,
  stylesListsSystemCradSubTitleStatusContainer,
  stylesListsSystemCradSubTitleStatusChipApp,
  stylesListsSystemCradSubTitleStatusChipAppText,
  stylesListsSystemCradSubTitleVerifyContainer,
  stylesListsSystemCradSubTitleVerifyChipApp,
  stylesListsSystemCradSubTitleVerifyChipAppText,
  stylesListsSystemCardRightContainer,
  stylesListsSystemCardRightTextInfo,
  stylesListsSystemMenuActions,
  stylesListsSystemMenuActionsTitleStyleText,
  stylesListsSystemFiltersViewText,
  stylesListsSystemViewIconPlus,
  stylesListsSystemSearchModalViewButton,
  stylesListsSystemSearchModalViewItem,
} from './stylesListsSystem';

import {
  stylesChangePermissionContainer,
  stylesChangePermissionTitleHeader,
  stylesChangePermissionTitle,
  stylesChangePermissionSubtitle,
  stylesChangePermissionFormItem,
  stylesChangePermissionFormButton,
  stylesChangePermissionFormButtonlabel,
  stylesChangePermissionLabelUserContainer,
  stylesChangePermissionNameUser,
  stylesChangePermissionRadioButtonlabelStyle,
  stylesChangePermissionRadioButtonChecked,
  stylesChangePermissionLabelUser,
  stylesChangePermissionDividerLabelUser,
} from './stylesChangePermission';

import {
  stylesViewUserContainer,
  stylesViewUserTitleHeader,
  stylesViewUserTitle,
  stylesViewUserSubtitle,
  stylesViewUserFormItem,
  stylesViewUserFormButton,
  stylesViewUserFormButtonlabel,
} from './stylesViewUser';

import {
  stylesSearchModalUsersViewContainer,
  stylesSearchModalUsersTitle,
  stylesSearchModalUsersViewButton,
} from './stylesSearchModalUsers';

import {
  stylesModalsContainer,
  stylesModalsContentContainer,
} from './stylesModals';

import {
  stylesViewsPagesContainer,
  stylesViewsPagesTitleHeader,
  stylesViewsPagesTitle,
  stylesViewsPagesSubtitle,
  stylesViewsPagesFormItem,
  stylesViewsPagesBackgroundItem,
  stylesViewsPagesTextItem,
  stylesViewsPagesStatusViewItem,
  stylesViewsPagesFormButton,
  stylesViewsPagesFormButtonlabel,
  stylesViewsPagesCenterText,
  stylesViewsPagesSubtitleErrorAlert,
  stylesViewsPagesWarningTextInput,
} from './stylesViewsPages';

import {
  stylesChipsStatusContainer,
  stylesChipsStatusChipApp,
  stylesChipsStatusChipAppText,
  stylesChipsVerifyContainer,
  stylesChipsVerifyChipApp,
  stylesChipsVerifyChipAppText,
} from './stylesChips';


import {
  stylesSelectBoxRadioButtonlabelStyle,
  stylesSelectBoxRadioButtonChecked,
  stylesSelectBoxHeaderContainer,
  stylesSelectBoxHeaderTitleView,
  stylesSelectBoxHeaderTitleText,
  stylesSelectBoxHeaderSearchContainer,
  stylesSelectBoxHeaderSearchInputView,
  stylesSelectBoxHeaderSearchButtonView,
} from './stylesSelectBox';

import {
  stylesTabBarSystemContainer,
  stylesTabBarSystemTabStyles,
  stylesTabBarSystemLabelStyle,
  stylesTabBarSystemIndicatorStyle,
} from './stylesTabBarSystem';

const styles = StyleSheet.create({
  stylesLayoutSafeAreaView,
  stylesLayoutContainerView,
  stylesLayoutContainerKeyboardAvoidingView,
  stylesLayoutContainerScrollView,
  styleHeaderContainerSafeAreaView,
  styleHeaderContainerView,
  styleHeaderButtonMenuDrawer,
  styleHeaderButtonMenuAction,
  styleHeaderDividerMenuAction,
  styleHeaderIconLogo,
  stylesCustomDrawerContainerView,
  stylesCustomDrawerImageLogo,
  stylesCustomDrawerTextWellcome,
  stylesCustomDrawerTextUserName,
  stylesCustomDrawerLabelStyleDrawerItem,
  stylesDrawerLabelStyleDrawerItem,
  stylesSignUpContainer,
  stylesSignUpTitleHeader,
  stylesSignUpTitle,
  stylesSignUpSubtitle,
  stylesSignUpFormItem,
  stylesSignUpFormButton,
  stylesSignUpFormButtonlabel,
  stylesSignUpFormButtonViewAccessLogin,
  stylesSignUpFormButtonTextAccessLogin,
  stylesSignUpAcceptConditionsView,
  stylesSignUpAcceptConditionsViewCheckbpx,
  stylesSignUpAcceptConditionsText,
  stylesSignInContainer,
  stylesSignInTitleHeader,
  stylesSignInTitle,
  stylesSignInSubtitle,
  stylesSignInFormItem,
  stylesSignInFormButton,
  stylesSignInFormButtonlabel,
  stylesSignInFormButtonViewAccessLogin,
  stylesSignInFormButtonTextAccessLogin,
  stylesSignInAcceptConditionsView,
  stylesSignInAcceptConditionsViewCheckbpx,
  stylesSignInAcceptConditionsText,
  stylesSnackbarWrapperStyle,
  stylesSnackbarTitleHeader,
  stylesSnackbarmsgText,
  stylesProfileContainer,
  stylesProfileTitleHeader,
  stylesProfileTitle,
  stylesProfileSubtitle,
  stylesProfileFormItem,
  stylesProfileFormButton,
  stylesProfileFormButtonlabel,
  stylesProfileFormButtonDesactive,
  stylesProfileFormButtonDesactiveText,
  stylesAlertYesOrNoIcon,
  stylesAlertYesOrNoIconError,
  stylesAlertYesOrNoIconSuccess,
  stylesAlertYesOrNoIconWarning,
  stylesAlertYesOrNoIconInfo,
  stylesAlertYesOrNoContainer,
  stylesAlertYesOrNoText,
  stylesAlertYesOrNoViewButton,
  stylesAlertYesOrNoButton,
  stylesAlertYesOrNoButtonLabel,
  stylesAlertYesOrNoTextTitle,
  stylesChangePasswordContainer,
  stylesChangePasswordTitleHeader,
  stylesChangePasswordTitle,
  stylesChangePasswordSubtitle,
  stylesChangePasswordFormItem,
  stylesChangePasswordFormButton,
  stylesChangePasswordFormButtonlabel,
  stylesChangePasswordFormButtonDesactive,
  stylesChangePasswordFormButtonDesactiveText,
  stylesResetPasswordContainer,
  stylesResetPasswordTitleHeader,
  stylesResetPasswordTitle,
  stylesResetPasswordSubtitle,
  stylesResetPasswordFormItem,
  stylesResetPasswordFormButton,
  stylesResetPasswordFormButtonlabel,
  stylesListsSystemContainer,
  stylesListsSystemFiltersView,
  stylesListsSystemFilterTextView,
  stylesListsSystemFilterText,
  stylesListsSystemContainerViewList,
  stylesListsSystemViewCard,
  stylesListsSystemCardRightStyle,
  stylesListsSystemCardTitleStyle,
  stylesListsSystemCardSubtitleStyle,
  stylesListsSystemListEmptyContainer,
  stylesListsSystemListEmptyTextMsg,
  stylesListsSystemListEmptyTextSubMsg,
  stylesListsSystemCradSubTitleStatusContainer,
  stylesListsSystemCradSubTitleStatusChipApp,
  stylesListsSystemCradSubTitleStatusChipAppText,
  stylesListsSystemCradSubTitleVerifyContainer,
  stylesListsSystemCradSubTitleVerifyChipApp,
  stylesListsSystemCradSubTitleVerifyChipAppText,
  stylesListsSystemCardRightContainer,
  stylesListsSystemCardRightTextInfo,
  stylesListsSystemMenuActions,
  stylesListsSystemMenuActionsTitleStyleText,
  stylesListsSystemFiltersViewText,
  stylesListsSystemViewIconPlus,
  stylesListsSystemSearchModalViewButton,
  stylesListsSystemSearchModalViewItem,
  stylesChangePermissionContainer,
  stylesChangePermissionTitleHeader,
  stylesChangePermissionTitle,
  stylesChangePermissionSubtitle,
  stylesChangePermissionFormItem,
  stylesChangePermissionFormButton,
  stylesChangePermissionFormButtonlabel,
  stylesChangePermissionLabelUserContainer,
  stylesChangePermissionNameUser,
  stylesChangePermissionRadioButtonlabelStyle,
  stylesChangePermissionRadioButtonChecked,
  stylesChangePermissionLabelUser,
  stylesChangePermissionDividerLabelUser,
  stylesModalsContainer,
  stylesModalsContentContainer,
  stylesSearchModalUsersViewContainer,
  stylesSearchModalUsersTitle,
  stylesSearchModalUsersViewButton,
  stylesViewUserContainer,
  stylesViewUserTitleHeader,
  stylesViewUserTitle,
  stylesViewUserSubtitle,
  stylesViewUserFormItem,
  stylesViewUserFormButton,
  stylesViewUserFormButtonlabel,
  stylesViewsPagesContainer,
  stylesViewsPagesTitleHeader,
  stylesViewsPagesTitle,
  stylesViewsPagesSubtitle,
  stylesViewsPagesFormItem,
  stylesViewsPagesBackgroundItem,
  stylesViewsPagesTextItem,
  stylesViewsPagesStatusViewItem,
  stylesViewsPagesFormButton,
  stylesViewsPagesFormButtonlabel,
  stylesViewsPagesCenterText,
  stylesViewsPagesSubtitleErrorAlert,
  stylesViewsPagesWarningTextInput,
  stylesChipsStatusContainer,
  stylesChipsStatusChipApp,
  stylesChipsStatusChipAppText,
  stylesChipsVerifyContainer,
  stylesChipsVerifyChipApp,
  stylesChipsVerifyChipAppText,
  stylesSelectBoxRadioButtonlabelStyle,
  stylesSelectBoxRadioButtonChecked,
  stylesSelectBoxHeaderContainer,
  stylesSelectBoxHeaderTitleView,
  stylesSelectBoxHeaderTitleText,
  stylesSelectBoxHeaderSearchContainer,
  stylesSelectBoxHeaderSearchInputView,
  stylesSelectBoxHeaderSearchButtonView,
  stylesTabBarSystemContainer,
  stylesTabBarSystemTabStyles,
  stylesTabBarSystemLabelStyle,
  stylesTabBarSystemIndicatorStyle,
});

export default styles;